---
# tasks file for ansible-role-pi-baseline
- name: Set authorized ssh keys (GitHub)
  ansible.posix.authorized_key:
    key: https://github.com/{{ github_user_for_ssh_key }}.keys
    user: "{{ ansible_user }}"
    comment: "github-{{ github_user_for_ssh_key }}"
  when:
    - github_ssh_key

- name: Set authorized ssh keys (Local)
  ansible.posix.authorized_key:
    key: '{{ auth_keys_local_path }}'
    user: "{{ ansible_user }}"
    comment: "Authorized SSH Keys"
  when:
    - not github_ssh_key

- name: Lock user password 
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    password_lock: true

- name: Set timezone
  ansible.builtin.lineinfile:
    path: /etc/timezone
    regexp: "^"
    line: "{{ timezone }}"

- name: Set localtime
  ansible.builtin.file:
    src: /usr/share/zoneinfo/{{ timezone }}
    dest: /etc/localtime
    state: link

- name: Set Hostname from Inventory
  ansible.builtin.lineinfile:
    path: /etc/hostname
    regexp: "^"
    line: '{{ inventory_hostname }}'
  notify: Reboot Host

- name: Update hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1      {{ inventory_hostname }}"
  notify: Reboot Host

- name: Install UFW Package 
  ansible.builtin.apt:
    name:
      - ufw
    force_apt_get: true
    state: present
  when:
    - enable_ufw

- name: Enable UFW Service
  community.general.ufw:
    state: enabled 
    default: reject
  when:
    - enable_ufw

- name: Add SSH to Allowed Services
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp
    src: '{{ item }}'
    comment: Allow SSH from Private Networks
  with_items:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  when: 
    - enable_ufw

- name: Set DNS Servers
  ansible.builtin.blockinfile:
    path: /etc/dhcpcd.conf
    block: |
      interface {{ static_interface }}
      static ip_address={{ ansible_host }}{{ static_subnet_mask }}
      static routers={{ static_gateway }}
      static domain_name_servers={{ static_dns }}
      noipv6
  notify: Restart dhcpcd
  when:
    - static_address
